"""Constants for the flake8_scout_rule plugin."""
import re

CODE_WITH_VIOLATION_COUNT_REGEX = re.compile(
    r"(?P<code>([A-Z]{1,3}[0-9]{1,3})){(?P<count>(\d+))}", re.IGNORECASE
)

TRACKED_VIOLATIONS_LINE_REGEX = re.compile(
    r"(?P<filename>[\S+ ]*\.py):\s*(?P<codes>([A-Z]+[0-9]+{\d+}(?:[,\s]+)?)+)", re.IGNORECASE
)

DEFAULT_FLAKE8_FILE = """[flake8]
exclude =
    # No need to traverse our git directory
    .git,
    # There's no value in checking cache directories
    __pycache__,
    # The conf file is mostly autogenerated, ignore it
    docs/source/conf.py,
    # The old directory contains Flake8 2.0
    old,
    # This contains our built documentation
    build,
    # This contains builds of flake8 that we don't want to check
    dist

[flake8_scout_rule]
per_file_violations_tracked =
"""
