import argparse
import configparser
import fileinput
import os
import random
import string
from collections import Counter
from itertools import groupby
from shutil import move
from typing import List, Optional

from flake8 import LOG
from flake8.defaults import NOQA_INLINE_REGEXP
from flake8.exceptions import FailedToLoadPlugin
from flake8.formatting.default import Default
from flake8.options.config import _find_config_file
from flake8.options.manager import OptionManager
from flake8.violation import Violation
import re

from flake8_scout_rule.data_classes import ViolationsByLine, ViolationsByCount, ViolationsByFile, \
    PerFileViolationsTracked, Flake8ScoutRuleConfigurations, ExistingViolationsByCount

CODE_WITH_VIOLATION_COUNT_REGEX = re.compile(r"(?P<code>([A-Z]{1,3}[0-9]{1,3}))(?P<count>{(\d+)})", re.IGNORECASE)

TRACKED_VIOLATIONS_LINE_REGEX = re.compile(
    r"(?P<filename>[\S+ ]*\.py):\s*(?P<codes>([A-Z]+[0-9]+{\d+}(?:[,\s]+)?)+)", re.IGNORECASE
)

class Flake8ScoutRuleFormatter(Default):
    """A formatter that collects all violations in the format phase and corrects them
    in the stop phase."""

    violations: List[Violation] = []
    per_file_violations_tracked: List[PerFileViolationsTracked] = []

    def __init__(self, options: argparse.Namespace) -> None:
        # Even though to use this flake8 reporter you need to pass in --format=scout,
        # override the default format to "default" so the users can still see the normal
        # collected violations, before agreeing to add the # noqa annotations to them.
        options.format = "default"
        super().__init__(options)
        if self.options.no_update_flake8_file:
            return

        # Validate the flake8 configuration file's per_file_violations_tracked key is formatted
        # correctly, if it exists
        configurations = self.load_raw_per_file_violations_tracked()
        if configurations:
            self.per_file_violations_tracked = self.format_per_file_violations_tracked(configurations)

    @staticmethod
    def load_raw_per_file_violations_tracked(add_defaults: bool = False) -> Optional[Flake8ScoutRuleConfigurations]:
        """Loads the raw per_file_violations_tracked string from the flake8 configuration file."""
        config_file = _find_config_file(os.getcwd())
        if not config_file:
            if add_defaults:
                config_file = os.path.join(os.getcwd(), ".flake8")
                print(f"No flake8 config file found, creating a default one at '{config_file}'")
                with open(config_file, "w") as f:
                    f.write("""[flake8]
                exclude = 
                    # No need to traverse our git directory
                    .git,
                    # There's no value in checking cache directories
                    __pycache__,
                    # The conf file is mostly autogenerated, ignore it
                    docs/source/conf.py,
                    # The old directory contains Flake8 2.0
                    old,
                    # This contains our built documentation
                    build,
                    # This contains builds of flake8 that we don't want to check
                    dist

                [flake8_scout_rule]
                per_file_violations_tracked =
                """)
                return Flake8ScoutRuleFormatter.load_raw_per_file_violations_tracked(add_defaults)
            else:
                LOG.debug("No flake8 config file found during the initialization of the "
                          "flake8_scout_rule plugin, continuing plugin execution.")
                return

        config = configparser.ConfigParser()
        config.read(config_file)
        if "flake8_scout_rule" not in config.sections():
            if add_defaults:
                print("Didn't find a [flake8_scout_rule] section in the flake8 configuration file, "
                      "adding it now.")
                config.add_section("flake8_scout_rule")
                config["flake8_scout_rule"]["per_file_violations_tracked"] = ""
                with open(config_file, "w") as f:
                    config.write(f)
                return Flake8ScoutRuleFormatter.load_raw_per_file_violations_tracked(add_defaults)
            else:
                LOG.debug("No [flake8_scout_rule] section found in the flake8 configuration file "
                          "during the initialization of the flake8_scout_rule plugin, continuing "
                          "plugin execution")
                return

        flake8_scout_rule_section = config["flake8_scout_rule"]
        raw_per_file_violations_tracked = flake8_scout_rule_section.get("per_file_violations_tracked")
        if raw_per_file_violations_tracked is None:
            if add_defaults:
                flake8_scout_rule_section["per_file_violations_tracked"] = ""
                with open(config_file, "w") as f:
                    config.write(f)
                return Flake8ScoutRuleFormatter.load_raw_per_file_violations_tracked(add_defaults)
            else:
                LOG.debug("No per_file_violations_tracked key found in the [flake8_scout_rule] "
                          "section of the flake8 configuration file during the initialization of "
                          "the flake8_scout_rule plugin, continuing plugin execution")
                return
        return Flake8ScoutRuleConfigurations(
            config_file=config_file,
            configparser=config,
            raw_per_file_violations_tracked=raw_per_file_violations_tracked
        )

    @staticmethod
    def format_per_file_violations_tracked(configurations: Flake8ScoutRuleConfigurations) -> List[PerFileViolationsTracked]:
        """Checks if the [flake8_scout_rule] section of the flake8 config file is formatted
        correctly.  If it's formatted incorrectly, raise an error here."""
        raw_per_file_violations_tracked = configurations.raw_per_file_violations_tracked
        # If the per_file_violations_tracked key is empty, just return an empty list
        if not raw_per_file_violations_tracked:
            return []

        current_file_violations_tracked = []
        lines_not_parsed = []
        for line in raw_per_file_violations_tracked.split("\n"):
            # If the line is empty, just skip it
            if not line:
                continue

            match = TRACKED_VIOLATIONS_LINE_REGEX.match(line)
            if not match:
                lines_not_parsed.append(line)
                continue

            filename = match.group("filename").strip()
            # TODO: Don't do anything now, maybe in the future, remove it from the
            # per_file_violations_tracked. For now, just check if the file exists and log a
            # warning if it doens't exist
            full_filename = os.path.join(os.getcwd(), filename)
            if not os.path.exists(full_filename):
                LOG.warning(f"File '{full_filename}' from the flake8 config file "
                            "per_file_violations_tracked key does not exist, so it will have no"
                            "functional impact.")

            codes = [m.strip() for m in match.group("codes").split(",")]
            issue_with_single_code = False
            violations_by_count = []
            for code in codes:
                code_match = CODE_WITH_VIOLATION_COUNT_REGEX.match(code)
                if not code_match:
                    lines_not_parsed.append(line)
                    issue_with_single_code = True
                    break
                violations_by_count.append(
                    ViolationsByCount(
                        filename=filename,
                        code=code,
                        count=int(code_match.group("count"))
                    )
                )
            if not issue_with_single_code:
                current_file_violations_tracked.append(PerFileViolationsTracked(
                    filename=filename,
                    violations_by_count=violations_by_count
                ))
        if lines_not_parsed:
            lines_not_parsed_joined = "\n\t".join(lines_not_parsed)
            raise FailedToLoadPlugin(
                "flake8-scout-rule",
                Exception("Failed to parse the following lines from the "
                "per_file_violations_tracked key in the [flake8_scout_rule] section of the flake8 "
                f"configuration file '{configurations.config_file}': \n{lines_not_parsed_joined}")
            )
        return current_file_violations_tracked

    @classmethod
    def add_options(cls, parser: OptionManager) -> None:
        """Add a flake8 --no-review-prompt and --no-update-flake8-file option to the OptionsManager."""
        cls.option_manager = parser
        no_review_prompt_help = (
            "(Default: true) Automatically update files with violations without prompting the user "
            "to review the violations."
        )
        parser.add_option(
            "--no-review-prompt",
            action="store_true",
            default=False,
            help=no_review_prompt_help,
            parse_from_config=True,
        )

        no_update_flake8_file_help = (
            "(Default: false) Stop from automatically creating/updating the flake8 configuration "
            "file's [flake8_scout_rule] section with the violations that were found in this run."
        )
        parser.add_option(
            "--no-update-flake8-file",
            action="store_true",
            default=False,
            help=no_update_flake8_file_help,
            parse_from_config=True,
        )

    @staticmethod
    def existing_violations_by_count_per_file(filename: str) -> ExistingViolationsByCount:
        """Returns the existing violations by count for the specified file."""
        filepath = os.path.join(os.getcwd(), filename)

        with open(filepath, 'r', encoding='utf-8') as f:
            file_content = f.read()

        evbc = ExistingViolationsByCount(filename=filename, violations_by_count=[])
        matches = re.findall(NOQA_INLINE_REGEXP, file_content)
        error_codes = []

        for match in matches:
            if not match:
                continue
            codes = [c.strip() for c in re.split(r",\s*", match[0])]
            error_codes.extend(codes)
        counter = Counter(error_codes)




    def format(self, error: Violation) -> str:
        """Instance of format from the Default formatter interface."""
        self.violations.append(error)
        return super().format(error)

    def stop(self):
        """Instance of stop from the Default formatter interface."""
        if not self.violations:
            print("No violations found, so nothing to add '# noqa: <errors>' to. Exiting.")
            return

        print(f"\nFound {len(self.violations)} violations.")
        if not self.options.no_review_prompt:
            response = self.prompt_for_corrections()
            if not response:
                print("Not correcting violations, exiting.")
                return

        violations_by_file_by_line = self._noqa_annotation_adder()

        if self.options.no_update_flake8_file:
            print("Not updating the flake8 configuration file, exiting.")
            return

        # Now add the defaults if they don't exist yet
        configurations = self.load_raw_per_file_violations_tracked(add_defaults=True)
        # If no per_file_violations_tracked exist yet, we can just write the new ones, don't need
        # to reconcile with existing ones
        if not self.per_file_violations_tracked:
            pfvt = "\n".join([vbc.violations_by_count_string for vbc in violations_by_file_by_line])
            configurations.configparser["flake8_scout_rule"]["per_file_violations_tracked"] = pfvt
            with open(configurations.config_file, "w") as f:
                configurations.configparser.write(f)
        else:




        print("\nDone")

    @staticmethod
    def _update_lines_in_file(violations: List[ViolationsByLine]) -> None:
        """
        Updates lines in the specified file by adding '# noqa: <errors>' annotations.

        This method assumes that the violations are all part of the same file

        It creates a backup of the file before making any changes and
        restores the original file in case of an error during the update process.

        :param violations: A list of violations grouped by line within a file.
        :type violations: List[ViolationsByLine]
        """
        backup_extension = f".bak_{Flake8ScoutRuleFormatter._random_letters(5)}"
        filename = violations[0].filename
        backup_file = f"{filename}{backup_extension}"
        try:
            with fileinput.input(files=filename, inplace=True, backup=backup_extension) as file:
                for line in file:
                    found = False
                    file_lineno = file.filelineno()
                    for violation in violations:
                        if violation.line_number == file_lineno:
                            found = True
                            print(violation.add_noqa_to_line)
                            break
                    if not found:
                        print(line, end="")
        except Exception:
            print(f"Error updating file {filename}")
            move(backup_file, filename)
            raise
        finally:
            os.remove(f"{filename}{backup_extension}")

    @staticmethod
    def prompt_for_corrections() -> bool:
        """
        Prompts the user to decide whether to correct violations inline.

        This method repeatedly asks the user for input until a valid response ('y' or 'n')
        is provided. It returns True if the user chooses to correct the violations, and False
        otherwise.

        :return: True if the user wants to correct the violations, False otherwise.
        :rtype: bool
        """
        while True:
            response = input("Do you want to correct these violations inline now? (y/n): ")
            formatted_response = response.strip().lower()[0:1]
            if formatted_response in ["y", "n"]:
                return formatted_response == "y"
            else:
                print("Invalid input. Please enter 'y' or 'n'.")

    @staticmethod
    def _group_violations_by_file_and_line(violations: List[Violation]) -> List[ViolationsByFile]:
        """
        Groups violations by file.

        This method processes a list of violations and groups them by the filename.
        It ensures that all violations belonging to the same file are grouped together
        in a list.

        :param violations: A list of `Violation` objects to be grouped by file.
        :type violations: List[Violation]
        :return: A list of lists, where each inner list contains `Violation` objects for a single
        file.
        :rtype: List[ViolationsByFile]
        """
        grp_by_filename = groupby(violations, key=lambda v: v.filename)
        violations_by_file = [
            ViolationsByFile(filename=key, violations=list(grp)) for key, grp in grp_by_filename
        ]
        violations_by_file.sort(key=lambda vbf: vbf.filename)
        for vbf in violations_by_file:
            vbf.violations_by_line = Flake8ScoutRuleFormatter._group_file_violations_by_line(vbf)
            vbf.violations_by_count = Flake8ScoutRuleFormatter._group_file_violations_by_count(vbf)
        return violations_by_file

    @staticmethod
    def _group_file_violations_by_line(
        violations_by_file: ViolationsByFile,
    ) -> List[ViolationsByLine]:
        """
        Groups violations by line within a file.

        This method processes a list of violations from the whole flake8 run, and groups them by
        line number within each file. It ensures that multiple violations on the same line are
        combined into a single `ViolationsByLine` object.

        :param violations: A list of `Violation` objects to be grouped by line.
        :type violations: List[Violation]
        :return: A list of `ViolationsByLine` objects, each representing a line with one or more
        violations.
        :rtype: List[ViolationsByLine]
        """
        violations_by_line: List[ViolationsByLine] = []
        for violation in violations_by_file.violations:
            found = False
            for vbl in violations_by_line:
                if vbl.line_number == violation.line_number:
                    vbl.codes.append(violation.code)
                    found = True
                    break
            if not found:
                vbl = ViolationsByLine(
                    filename=violation.filename,
                    line_number=violation.line_number,
                    physical_line=violation.physical_line,
                    codes=[violation.code],
                )
                violations_by_line.append(vbl)
        violations_by_line.sort(key=lambda vbl: vbl.line_number)
        return violations_by_line

    @staticmethod
    def _group_file_violations_by_count(
        violations_by_file: ViolationsByFile,
    ) -> List[ViolationsByCount]:
        """
        Groups violations by count within a file.

        This method processes a list of violations from the whole flake8 run, and groups them by
        count within each file. It ensures that multiple violations of the same type are
        combined
        """
        violations_by_count: List[ViolationsByCount] = []
        for violation in violations_by_file.violations:
            found = False
            for vbc in violations_by_count:
                if vbc.code == violation.code:
                    vbc.count += 1
                    found = True
                    break
            if not found:
                vbc = ViolationsByCount(filename=vbc.filename, code=violation.code, count=1)
                violations_by_count.append(vbc)
        violations_by_count.sort(key=lambda vbc: vbc.code)
        return violations_by_count

    def _noqa_annotation_adder(self) -> List[ViolationsByFile]:
        """
        Adds '# noqa: <errors>' annotations to lines in files with violations.

        The method groups violations by file and then by line within each file,
        ensuring that multiple violations on the same line are handled correctly.
        It creates a backup of each file before making any changes and restores the
        original file in case of an error during the update process.
        """
        no_review_prompt_prefix = "Automatically a" if self.options.no_review_prompt else "A"
        print(
            f"{no_review_prompt_prefix}dding '# noqa: <errors>' annotations to the files "
            "with violations now:"
        )
        violations_by_file_and_line = self._group_violations_by_file_and_line(self.violations)
        for file_violations in violations_by_file_and_line:
            LOG.debug(
                f"Adding '# noqa: <errors>' annotations to file: '{file_violations.filename}'"
            )
            self._update_lines_in_file(file_violations.violations_by_line)
            print(".", end="")
        return violations_by_file_and_line

    @staticmethod
    def _random_letters(num_letters: int) -> str:
        """Generates a random string of the specified length consisting of ASCII letters."""
        return "".join(random.choices(string.ascii_letters, k=num_letters))
